"""A PyTorch stream of sequences, generated by Stage B in memory for every item."""

from __future__ import annotations

from collections.abc import Iterator
from itertools import count
from pathlib import Path
from typing import Any

import numpy as np
import torch
from torch.utils.data import IterableDataset, get_worker_info

from video_bokeh.core._sequence_geometry import SampleConfig
from video_bokeh.scenes._compositor import (
    CollisionRetriesExhausted,
    render_scene,
    sample_scene,
)
from video_bokeh.scenes.generate import sample_n_objects

# A stream that skips this many seeds in a row will not recover: the parameters ask for
# more objects than the depth axis can hold apart. Failing beats spinning forever.
_MAX_SKIPS_IN_A_ROW = 100


class SequenceStream(IterableDataset):
    """An endless stream of sequences from ``library_root``, one new sequence per item.

    Each item is a dict of float32 tensors in ``[0, 1]``, frames first:

    - ``rgb`` (T, 3, H, W), the all-in-focus frames;
    - ``disparity`` (T, 1, H, W);
    - ``alpha`` (T, 1, H, W), the union of the objects' mattes;
    - ``object_alphas`` (T, n_objects_max, H, W), one matte per object in page order,
      zero past ``n_objects``, so every item has the same shape and the default collate
      batches them;

    plus ``n_objects`` and ``seed``, ints. Worker ``w`` of ``W`` takes seeds
    ``seed + w``, ``seed + w + W``, ...: workers never repeat each other, and one worker
    yields the scenes ``scenes.generate --seed`` writes, unquantized. A seed whose objects
    cannot be placed without colliding is skipped, as the writer skips it.

    Every new iterator starts again at ``seed``, so a loop that re-creates its iterator
    each epoch sees the same sequences again; change ``seed`` between runs. Assets are
    read from disk for every item. That is the first thing to cache if the stream cannot
    keep a training loop fed.
    """

    def __init__(
        self,
        library_root: Path,
        n_frames: int,
        size: int,
        n_objects_min: int = 1,
        n_objects_max: int = 5,
        seed: int = 0,
        cfg: SampleConfig | None = None,
    ) -> None:
        super().__init__()
        if not 1 <= n_objects_min <= n_objects_max:
            raise ValueError(
                f"need 1 <= n_objects_min <= n_objects_max, "
                f"got {n_objects_min} and {n_objects_max}",
            )
        self.library_root = library_root
        self.n_frames = n_frames
        self.size = size
        self.n_objects_min = n_objects_min
        self.n_objects_max = n_objects_max
        self.seed = seed
        self.cfg = cfg

    def __iter__(self) -> Iterator[dict[str, Any]]:
        info = get_worker_info()
        worker, workers = (info.id, info.num_workers) if info else (0, 1)
        skipped = 0
        for k in count():
            seq_seed = self.seed + worker + k * workers
            try:
                item = self._render(seq_seed)
            except CollisionRetriesExhausted:
                skipped += 1
                if skipped == _MAX_SKIPS_IN_A_ROW:
                    raise RuntimeError(
                        f"{skipped} seeds in a row up to {seq_seed} could not place "
                        f"{self.n_objects_min} to {self.n_objects_max} objects without "
                        "collisions; ask for fewer",
                    ) from None
                continue
            skipped = 0
            yield item

    def _render(self, seq_seed: int) -> dict[str, Any]:
        n_objects = sample_n_objects(seq_seed, self.n_objects_min, self.n_objects_max)
        scene = sample_scene(
            self.library_root,
            seed=seq_seed,
            n_frames=self.n_frames,
            size=self.size,
            n_objects=n_objects,
            cfg=self.cfg,
        )
        frames = render_scene(scene)
        placed = len(scene.objects)
        object_alphas = np.zeros(
            (len(frames), self.n_objects_max, self.size, self.size),
            dtype=np.float32,
        )
        for t, frame in enumerate(frames):
            object_alphas[t, :placed] = np.stack(frame.object_alphas)
        return {
            "rgb": torch.from_numpy(
                np.stack([f.rgb for f in frames]).transpose(0, 3, 1, 2) / 255.0,
            ).float(),
            "disparity": torch.from_numpy(np.stack([f.disparity for f in frames]))[
                :,
                None,
            ],
            "alpha": torch.from_numpy(np.stack([f.alpha for f in frames]))[:, None],
            "object_alphas": torch.from_numpy(object_alphas),
            "n_objects": placed,
            "seed": seq_seed,
        }
